config/routes.rb
DummyServer::Application.routes.draw do
  root to: 'rules#index'
  
  resources :rules do
    member do
      post 'clear'
    end
  end

  match '*path' => 'rules#hit'

end

app/models/hit.rb
# Records a request that matched a rule.
# A portion of the Rack request env, including HTTP headers,
# is stored in env.
class Hit < ActiveRecord::Base
  belongs_to :rule

  validates :env, presence: true

  serialize :env, Hash
end

app/models/rule.rb
# Specifies how to respond to requests meeting particular criteria.
class Rule < ActiveRecord::Base
  has_many :hits, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :precedence, numericality: {only_integer: true}
  validates :method_pattern, presence: true
  validates :path_pattern, presence: true
  validates :response_status, numericality: {only_integer: true}
  validates :delay, numericality: {only_integer: true}
  validate :response_headers_parseable

  # Ensure pattern fields are valid regexes.
  validates_each :method_pattern, :path_pattern do |record, attribtue, value|
    begin
      Regexp.new value
    rescue RegexpError => error
      record.errors.add attribute, 'must be a valid regex'
    end
  end

  # Ensure the response headers can be parsed.
  def response_headers_parseable
    response_headers_hash
  rescue HeaderParseError => error
    errors.add :response_headers, " could not be parsed: #{error.message}"
  end

  # Trying to override one of the headers Rails normally sets
  # appears to require using the same casing it uses.
  NORMALIZED_HEADERS = {
    'date' => 'Date',
    'connection' => 'Connection',
    'content-length' => 'Content-Length',
    'x-ua-compatiable' => 'X-Ua-Compatible',
    'x-runtime' => 'X-Runtime',
    'server' => 'Server',
    'etag' => 'ETag',
    'content-type' => 'Content-Type',
    'cache-control' => 'Cache-Control'
  }

  # Return the regular expression that HTTP methods must match.
  def method_regex
    Regexp.new method_pattern, 'i'
  end

  # Return the regular expression that paths must match.
  def path_regex
    Regexp.new path_pattern, 'i'
  end

  # Parse user-supplied raw headers into a hash.
  def response_headers_hash
    return {} unless response_headers
    result = {}
    prev = nil
    response_headers.each_line do |line|
      next if line.blank?
      if line[0..0].blank?
        raise HeaderParseError.new('Leading whitespace on first header line') unless prev
        prev << line.lstrip
      else
        key, value = line.split(':', 2)
        raise HeaderParseError.new('Missing header name') if key.blank?
        key = NORMALIZED_HEADERS[key.downcase] || key
        prev = value.lstrip!
        result[key] = prev
      end
    end
    result
  end

  class HeaderParseError < StandardError
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  # GET /rules
  def index
    @rules = Rule.order('precedence')

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /rules/1
  def show
    @rule = Rule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /rules/new
  def new
    @rule = Rule.new precedence: 5,
                     method_pattern: '.*',
                     path_pattern: '^/.*$',
                     response_status: 200,
                     delay: 0

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /rules/1/edit
  def edit
    @rule = Rule.find(params[:id])
  end

  # POST /rules
  def create
    @rule = Rule.new(params[:rule])

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /rules/1
  def update
    @rule = Rule.find(params[:id])

    respond_to do |format|
      if @rule.update_attributes(params[:rule])
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /rules/1
  def destroy
    @rule = Rule.find(params[:id])
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url }
    end
  end

  # POST /rules/1/clear
  # Can pass 'referrer' param to control redirect.
  def clear
    @rule = Rule.find(params[:id])
    @rule.hits.destroy_all

    respond_to do |format|
      format.html { redirect_to params[:referrer] || @rule }
    end
  end

  # /*
  def hit
    rule = Rule.order(:precedence).detect do |rule|
      request.method =~ rule.method_regex and request.path_info =~ rule.path_regex
    end

    if rule
      rule.hits.create env: env_hash,
                       body: request.raw_post
      sleep rule.delay if rule.delay > 0
      response.status = rule.response_status
      headers.merge! rule.response_headers_hash
      response.body = rule.response_text
      render text: response.body
    else
      raise ActionController::RoutingError.new('No matching route or rule')
    end
  end

private

  # Return a hash of the headers, with some dull ones filtered out.
  def env_hash
    hash = {}
    request.env.each do |key, value|
      hash[key] = value if key =~ /^(HTTP|REQUEST|REMOTE).*/
    end
    puts hash.to_s
    hash
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DummyServer</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rules/_form.html.haml
= form_for(@rule) do |f|
  
  - if @rule.errors.any?
    %p.errors
      = "#{pluralize(@rule.errors.count, 'error')} prohibited this rule from being saved:"
      %ul
        - @rule.errors.full_messages.each do |message|
          %li= message
  

  %dl.edit
    %dt= f.label :precedence
    %dd= f.number_field :precedence

    %dt= f.label :name
    %dd= f.text_field :name

    %dt= f.label :method_pattern
    %dd= f.text_field :method_pattern

    %dt= f.label :path_pattern
    %dd= f.text_field :path_pattern

    %dt= f.label :response_status
    %dd= f.number_field :response_status

    %dt= f.label :delay, 'Delay (seconds)'
    %dd= f.number_field :delay

    %dt= f.label :response_headers
    %dd= f.text_area :response_headers

    %dt= f.label :response_text
    %dd= f.text_area :response_text

  = f.submit

app/views/rules/edit.html.haml
%h1= "Edit #{@rule.name}"

= render 'form'

app/views/rules/index.html.haml
%h1 Mock Server Rules

%p.new-rule= link_to 'New Rule', new_rule_path

%table.rules
  %thead
    %th Precedence
    %th Name
    %th Hits
    %th Method
    %th Path
    %th Status
    %th Delay
    %th
    %th
    %th
  
  %tbody
    - @rules.each do |rule|
      %tr
        %td= rule.precedence
        %td= link_to rule.name, rule
        %td= rule.hits.count
        %td= rule.method_pattern
        %td= rule.path_pattern
        %td= rule.response_status
        %td= rule.delay
        %td= link_to 'edit', edit_rule_path(rule)
        %td= link_to 'destroy', rule, confirm: "Delete rule #{rule.name}?", method: :delete
        %td= link_to 'clear', clear_rule_path(rule, referrer: rules_path), confirm: "Clear hits for #{rule.name}?", method: :post

app/views/rules/new.html.haml
%h1 New Mock Server Rule

= render 'form'

app/views/rules/show.html.haml
%h1= "#{@rule.name}"

%p#notice= notice

.rule
  .precedence= "Precedence: #{@rule.precedence}"
  .hits= "Hits: #{@rule.hits.count}"
  .method-pattern= "Method: #{@rule.method_pattern}"
  .path-pattern= "Path: #{@rule.path_pattern}"
  .response-status= "Status: #{@rule.response_status}"
  .delay= "Delay: #{@rule.delay}"
  .edit= link_to 'edit', edit_rule_path(@rule)
  .destroy= link_to 'destroy', @rule, confirm: "Delete rule #{@rule.name}?", method: :delete
  .clear= link_to 'clear', clear_rule_path(@rule), confirm: "Clear hits for #{@rule.name}?", method: :post

- if @rule.hits.empty?
  %p Refresh this page to check for hits matching this rule.
- else
  %ul.hits
    - @rule.hits.order('created_at DESC').each do |hit|
      %li.hit
        %p.time= "Match at #{hit.created_at}"

        %dl.env
          - hit.env.each do |key, value|
            %dt= key
            %dd= value
        
        %pre.body= hit.body